# Not in use: currenlty circle CI is being used
# Because Travis doesn't let you build from private github dependencies
sudo: required
language: python
services:
- docker
before_install:
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
install:
- npm ci
- npm run build
script:
- echo "pass"
deploy:
  provider: script
  script: ./push_to_hub.sh
  on:
    all_branches: true
