version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1-browsers
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: npm ci
      - run: ./circle-environment.sh npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  build-docker:
    docker:
      - image: circleci/node:9.11.1-browsers
    steps:
      - checkout
      - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: dist
      - run: docker info
      - run: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD -e=$DOCKER_EMAIL
      - run: ./push_to_hub.sh
workflows:
  version: 2
  # build:
  #   jobs:
  #     - build
  build-and-push:
    jobs:
      - build
      - build-docker:
        requires:
          - build
