version: 2
jobs:
  build:
    docker:
      - image: matyasfodor/node-npm:9-6
    steps:
      - checkout
      - run: npm ci
      - run: ./.circleci/environment.sh npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  build-docker:
    docker:
      - image: matyasfodor/node-npm:9-6
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: dist
      - run: docker info
      - run: echo ${DOCKER_PASSWORD} | docker login -u=${DOCKER_USERNAME} --password-stdin
      - run: ./.circleci/push_to_hub.sh
workflows:
  version: 2
  build:
    jobs:
      - build
  build-and-push:
    jobs:
      - build
      - build-docker:
          requires:
            - build
    filters:
      branches:
        only:
          - devel
          - master
