version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1-browsers
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: npm ci
      - run: ./circle-environment.sh npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  build-docker:
    docker:
      - image: circleci/node:9.11.1-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - attach_workspace:
          at: dist
      - run: docker info
      - run: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD -e=$DOCKER_EMAIL
      - run: ./push_to_hub.sh
workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - build-docker:
          requires:
            - build
