apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: decaf-metabolica
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - app.dd-decaf.eu
    secretName: decaf-tls
  rules:
  - host: app.dd-decaf.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: decaf-metabolica-production
          servicePort: 80
